### ISSUE TITLE
1 .Add option to create visual studio c++ solution (sln) files  ,  2 add option to compile statically 

### ISSUE THREAD

**Issue by whiletrue111** [vorlac/godot-roguelite#12]
Hello 
 Great project i learning a ton .  
1. Can the cmake/ninja provide option to create vsc++ project solution ( sln ) ?
2. Can the cmake add option to create static lib and then compile statically with the engine ?

At  first  only for windows . 
Thanks

**Comment by vorlac** [comment]
i can check what you'd end up with if you change the cmake generator from Ninja to Visual Studio 2022 project files, but i have a feeling it's not going to end up with anything too clean because of what I do with the engine's codebase to get it working well in an IDE. This setup was kind of created to specifically not have to work with vcxproj/sln files since cmake ends up being easier/cleaner once you've figured out the language a bit.

statically linking the library with the engine wouldn't work for gdextension. that sounds more like how you'd approach working with a godot module (where you extend the engine directly). using gdextension, the library is built completely separate from the engine (it just requires the godot-cpp library to have everything it needs to interface with the engine though dynamic bindings that are created at runtime).
